WondyRestaurant/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WondyRestaurant.Data;
using WondyRestaurant.Models;
using WondyRestaurant.Models.OrderDetailsViewModel;
using WondyRestaurant.Utility;

namespace WondyRestaurant.Controllers
{
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public OrderDetailsCart DetailsCart { get; set; }

        public CartController(ApplicationDbContext db)
        {
            _db = db;

        }
        public IActionResult Index()
        {
            var detailsCart = new OrderDetailsCart()
            {
                OrderHeader = new OrderHeader(),
              //  ListCart = new List<ShoppingCart>()
                
            };
            detailsCart.OrderHeader.OrderTotal = 0;
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var cart = _db.ShoppingCart.Where(c => c.ApplicationUserId == claim.Value);
            if (cart!= null)
            {
                detailsCart.ListCart = cart.ToList();
            }
            foreach (var list in detailsCart.ListCart)
            {
                list.MenuItem = _db.MenuItem.FirstOrDefault(m => m.Id == list.MenuItemId);
                detailsCart.OrderHeader.OrderTotal += list.MenuItem.Price * list.Count;
                if (list.MenuItem.Description.Length > 100)
                {
                    list.MenuItem.Description = list.MenuItem.Description.Substring(0, 99) + "...";
                }


            }
            detailsCart.OrderHeader.PickupTime = DateTime.Now;
            return View(detailsCart);
        }

        [HttpPost, ActionName("Index")]
        [ValidateAntiForgeryToken]        
        public IActionResult IndexPOST()
        {
            // We will find user id here
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            DetailsCart.ListCart = _db.ShoppingCart.Where(c => c.ApplicationUserId == claim.Value).ToList();

            DetailsCart.OrderHeader.OrderDate = DateTime.Now;
            DetailsCart.OrderHeader.UserId = claim.Value;
            DetailsCart.OrderHeader.Status = SD.StatusSubmited;
            OrderHeader orderHeader = DetailsCart.OrderHeader;
            _db.OrderHeader.Add(orderHeader);
            _db.SaveChanges();

            
            foreach (var item in DetailsCart.ListCart)
            {
                item.MenuItem = _db.MenuItem.FirstOrDefault(m => m.Id == item.MenuItemId);
                OrderDetails orderdetails = new OrderDetails()
                {
                    MenuItemId = item.MenuItemId,
                    OrderId = orderHeader.Id,
                    Description = item.MenuItem.Description,
                    Name = item.MenuItem.Name,
                    Price = item.MenuItem.Price,
                    Count = item.Count
                };
                _db.OrderDetails.Add(orderdetails);

            }
            _db.ShoppingCart.RemoveRange(DetailsCart.ListCart);
            _db.SaveChanges();
            // update the session

            HttpContext.Session.SetInt32("CartCount", 0);

            return RedirectToAction("Confirm", "Order", new { id = orderHeader.Id });            


        }
       

        public IActionResult Plus(int cartId)
        {
            var userFromdb = _db.ShoppingCart.Where(c => c.Id == cartId).FirstOrDefault();
            userFromdb.Count ++;


            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        

        public IActionResult Minus(int cartId)
        {
            var cartFromdb = _db.ShoppingCart.Where(c => c.Id == cartId).FirstOrDefault();

            if (cartFromdb.Count == 1)
            {
                _db.ShoppingCart.Remove(cartFromdb);

                _db.SaveChanges();

                // update the session

                var cnt = _db.ShoppingCart.Where(c => c.ApplicationUserId == cartFromdb.ApplicationUserId).ToList().Count;

                HttpContext.Session.SetInt32("cartCount", cnt);

            }
            else
            {

                cartFromdb.Count -= 1;
                _db.SaveChanges();
            }

            return RedirectToAction(nameof(Index));
        }


        
    }
}

WondyRestaurant/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WondyRestaurant.Data;
using WondyRestaurant.Models;
using WondyRestaurant.Utility;

namespace WondyRestaurant.Controllers
{
    [Authorize(Roles = SD.AdminEndUser)]
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Category.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .SingleOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
               await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        
        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category.SingleOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
       
        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }
       
        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .SingleOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

       

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Category.SingleOrDefaultAsync(m => m.Id == id);
            _context.Category.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        
        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.Id == id);
        }
    }
}

WondyRestaurant/Controllers/CouponsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WondyRestaurant.Data;
using WondyRestaurant.Models;
using WondyRestaurant.Utility;

namespace WondyRestaurant.Controllers
{
    [Authorize(Roles = SD.AdminEndUser)]
    public class CouponsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CouponsController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _db.Coupons.ToListAsync());
        }


        //GET Coupons
        public IActionResult Create()
        {
            return View();
        }

        //POST Create Coupons
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Coupons coupons)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files[0] != null && files[0].Length > 0)
                {
                    byte[] p1 = null;
                    using (var fs1 = files[0].OpenReadStream())
                    {
                        using (var ms1 = new MemoryStream())
                        {
                            fs1.CopyTo(ms1);
                            p1 = ms1.ToArray();
                        }
                    }
                    coupons.Picture = p1;
                    _db.Coupons.Add(coupons);
                    await _db.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(coupons);
        }

        //GET Edit Coupons
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var coupon = await _db.Coupons.SingleOrDefaultAsync(m => m.Id == id);
            if (coupon == null)
            {
                return NotFound();
            }
            return View(coupon);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Coupons coupons)
        {
            if (id != coupons.Id)
            {
                return NotFound();
            }

            var couponFromDb = await _db.Coupons.Where(c => c.Id == id).FirstOrDefaultAsync();

            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files[0] != null && files[0].Length > 0)
                {
                    byte[] p1 = null;
                    using (var fs1 = files[0].OpenReadStream())
                    {
                        using (var ms1 = new MemoryStream())
                        {
                            fs1.CopyTo(ms1);
                            p1 = ms1.ToArray();
                        }
                    }
                    couponFromDb.Picture = p1;
                }
                couponFromDb.MinimumAmount = coupons.MinimumAmount;
                couponFromDb.Name = coupons.Name;
                couponFromDb.Discount = coupons.Discount;
                couponFromDb.CouponType = coupons.CouponType;
                couponFromDb.IsActive = coupons.IsActive;

                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(coupons);
        }


        //GET Delete Coupons
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var coupon = await _db.Coupons.SingleOrDefaultAsync(m => m.Id == id);
            if (coupon == null)
            {
                return NotFound();
            }
            return View(coupon);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var coupons = await _db.Coupons.SingleOrDefaultAsync(m => m.Id == id);
            _db.Coupons.Remove(coupons);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

WondyRestaurant/Views/Shared/_CreateButtonPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<p>
    <a asp-action="Create"  class="btn btn-primary">
        <i class="fas fa-plus"></i>
        &nbsp; Create New
    </a>
</p>

WondyRestaurant/Views/Shared/_IndividualOrderDetails.cshtml
@model WondyRestaurant.Models.OrderDetailsViewModel.OrderDetailsViewModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="row rounded" style="background-color:aliceblue; padding-bottom: 20px; margin-bottom:3px;">
    <div class="col-6">
        <div style="color:maroon"> Order Number: @Model.OrderHeader.Id</div>
        <ul class="text-info">
            @foreach (var item in Model.OrderDetails)
            {
                <li>@item.Name x  @item.Count</li>
            }
        </ul>
    </div>

    <div class="col-6">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-4">
                Order Total:
            </div>
            <div class="col-6">
                $@Model.OrderHeader.OrderTotal
            </div>
        </div>

        <div class="row">
            <div class="col-2"></div>
            <div class="col-4">
                Pick Up Time :
            </div>
            <div class="col-6">
                @Model.OrderHeader.PickupTime.ToLongDateString() &nbsp; @Model.OrderHeader.PickupTime.ToShortTimeString()
            </div>
        </div>

        <div class="row">
            <div class="col-2"></div>
            <div class="col-4">
                Order Status :
            </div>
            <div class="col-6">
                @Model.OrderHeader.Status
            </div>
        </div>

        <div class="row">
            <div class="col-2"></div>
            <div class="col-4">
                Comments :
            </div>
            <div class="col-6">
                @Model.OrderHeader.Comments
            </div>
        </div>

    </div>
</div>
<br />

WondyRestaurant/Views/Shared/_Layout.cshtml
@using WondyRestaurant.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WondyRestaurant</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />        
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/css/Typeahead.css" rel="stylesheet" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        <link href="~/css/jquery-ui.min.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link href="~/css/Typeahead.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        <link href="~/css/jquery-ui.min.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" asp-action="Index" asp-controller="Home"> Wondy Restaurant</a>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                @if (User.IsInRole(SD.AdminEndUser) || User.IsInRole(SD.CustomerEndUser))
                {
                    <li class="nav-item"> <a class="nav-link" asp-action="OrderHistory" asp-controller="Order"> Order History</a> </li>
                }

                @if (User.IsInRole(SD.AdminEndUser))
                {
                    <li class="nav-item dropdown">


                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Admin
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-controller="Categories" asp-action="Index">Category</a>
                            <a class="dropdown-item" asp-controller="Subcategories" asp-action="Index">Sub Category</a>
                            <a class="dropdown-item" asp-controller="MenuItems" asp-action="Index">Menu Items</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-controller="Coupons" asp-action="Index">Coupons</a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Order
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-action="ManageOrder" asp-controller="Order">Manage Order</a>
                            <a class="dropdown-item" asp-action="OrderPickUp" asp-controller="Order">Order Pickup</a>
                            <a class="dropdown-item" href="#">Download Order details </a>
                        </div>
                    </li>

                }

                @if (User.IsInRole(SD.AdminEndUser) || User.IsInRole(SD.CustomerEndUser))
                {
                    if (HttpContextAccessor.HttpContext.Session.GetInt32("cartCount") != null)
                    {


                    <li style="color: white;">
                        <a asp-action="Index" asp-controller="Cart" class="nav-link">
                            <i class="fas fa-shopping-cart"></i>
                            &nbsp;(@HttpContextAccessor.HttpContext.Session.GetInt32("cartCount"))
                        </a>
                        
                    </li>
                    }
                    else
                    {
                    <li style="color: white;">
                        <a asp-action="Index" asp-controller="Cart" class="nav-link">
                            <i class="fas fa-shopping-cart"></i>
                            &nbsp;(0)
                        </a>

                    </li>

                    }
                }
            </ul>
               

        </div>

        <div class="form-inline">
            @await Html.PartialAsync("_loginPartial")

        </div>

    </nav>

    <div class="container body-content">
        <br />
        @RenderBody()
        <br />
        <hr />

    </div>
    <footer class="footer">
        <div class="cont">
            <p class="text-muted">&copy; 2018 - WondyRestauran</p>

        </div>

    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/jquery-ui.min.js"></script>
    </environment>


    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/jquery-ui.min.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

WondyRestaurant/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

WondyRestaurant/Views/Shared/_TableButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td style="width: 150px;">
    <div class="btn-group" role="group">

        <a  class="btn btn-primary" href="@Url.Action("Edit/"+Model)">
            <i class="fas fa-edit"></i>
        </a>

        <a  class="btn btn-success" href="@Url.Action("details/"+Model)">
            <i class="far fa-list-alt"></i>
        </a>

        <a  class="btn btn-danger" href="@Url.Action("Delete/"+Model)">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>

</td>

WondyRestaurant/Views/Shared/_ThumbnailAreaPartial.cshtml
@model IEnumerable<MenuItem>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@if (Model.Count() > 0)
{
    foreach (var item in Model)
    {
        <div class="border border-info rounded col-12" style="margin-top:10px;margin-bottom:10px;padding:10px;">
            <div class="row">
                <div class="col-9">
                    <div class="row">
                        <div class="col-10">
                            <label class="text-primary" style="font-size:21px;color:maroon;">@item.Name</label>
                            <br />
                            <label class="badge badge-primary">@item.SubCategory.Name</label>
                            @if (item.Spicyness == "1")
                            {
                                <label class="badge badge-info">@MenuItem.EScipy.Spicy</label>
                            }
                            @if (item.Spicyness == "2")
                            {
                                <label class="badge badge-info">@MenuItem.EScipy.VerySpicy</label>
                            }
                        </div>
                        <div class="col-2 text-right" style="color:maroon">
                            <h4>$@item.Price</h4>
                        </div>
                    </div>
                    <div class="row col-12 text-justify">
                        <p>@item.Description</p>
                        <br />
                        <a asp-action="Details" class="btn btn-success" asp-route-id="@item.Id">Details</a>
                    </div>
                </div>
                <div class="col-3">
                    <img src="@item.Image" width="90%" style="border-radius:5px;border:1px solid #bbb9b9;" />
                </div>
            </div>
        </div>

    }

}